M48
; DRILL file {KiCad 9.0.4} date 2025-09-21T11:05:40+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-21T11:05:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X-2.89Y-43.695
X2.89Y-43.695
T2
X-21.5Y46.5
X-21.5Y-46.5
X21.5Y46.5
X21.5Y-46.5
M30
